### ISSUE TITLE
Remove header x-axis overflow

### ISSUE THREAD

**Issue by satv1r** [jaskiran-chhokar/raman-illusions#2]
On the header there appears to be an x-axis overflow on the right. This issue appears to be related to the video overlay. I wasn't able to observe the issue in the inspector/dev tools, only within normal browsing. 

I was able to replicate in both Brave (Chromium), and Safari. 

![Image of Overflow](https://user-images.githubusercontent.com/20546974/73766830-9b797d00-4744-11ea-9a0f-aa2333df3726.png)

**Comment by jaskiran-chhokar** [comment]
Changed the video background overlay width to 100% instead of 100vw.

**Comment by satv1r** [comment]
Perfect.
