### ISSUE TITLE
Optimize walk-around-magic video

### ISSUE THREAD

**Issue by jaskiran-chhokar** [jaskiran-chhokar/raman-illusions#3]
Optimize, reduce the size, and compress the walk-around-magic.mp4 video in the assets folder.

**Comment by satv1r** [comment]
[I've trimmed the clip down and removed the audio](https://drive.google.com/open?id=1tR8lyiv4NGvcJLLL9a4J1bu2VPFFGqiX). The new file size is 1.59MB, compared to 6.87MB with the original. We could potentially reduce it down even further if the video frame is going to be very small. I will mark this issue as closed.
